addons:
  apt:
    packages:
    - realpath
language: python
python:
- "3.6"
services: docker
env:
  global:
  - GITHUB_USER=joeblackwaslike
  - GITHUB_ORG=telephoneorg
  - DOCKER_USER=joeblackwaslike
  - DOCKER_ORG=telephoneorg
  # DOCKER_PASS
  - secure: "S5XUQoVr34yRLwf6QRw+F5RT3ZYqBsX5JOPETd3D0nxW3tRF+O7pia31u9MJviKAuTrASmY78u5rNHOHEhYNiO0gtBpiXTK0AxELzgCxm49JYb+vecsmsVgD6dfyEsnNYFfJFIZAau8CpnYndd21RVkpiiIPWWENgtzmuedvs4OEaC6Rl9jtYrDhqNZ2dLJPKdyBeSwrlpUg3yRtEX0LmJIRF7LYEeBUvEyZ7AJ/qQe9Nq0VSaSsdAh/0B+7YqAr47+LS/5UEtwgwzyrMpBtd+L0xZ0Rcl1plExyOIMeudaDeh1UuW4hpETe9h13vGxRjgp/Q51YDStKF3Qc6m/7bi0RFoMcyijxBcCbcO7f7ZZXcAGSSOVZUjyLY2Ewmawxy4yq7snuXnmUYHUhfvotcDtjYqQcOvtMYXAHbEN+zrcosZDIJXq442U6N6XwSubFFW6+fZD21ZXPkQRJSmVvNeFSJS3ZjtM4BgqZmT1PMkIuH5FWv/3uYFaS+DVZUihp484rS6BR5u/HMJl38MKYKPC5RVXnQn/jY8SadWh9u0hsymqLODHMGhTkX0coZUg2Hj8RBu3EcFFkLTHrmWDF40PlSu5ku24LEppYjACe9QSGz3dZpoplEqy2Oq0Ab39xxQ+VcLBz0ir0uHFlw4IHl2xhkSdT2peJw6FQSVyCSc4="
notifications:
  email:
    on_success: never
    on_failure: always
  slack:
    rooms:
    - secure: "GaHp43V7NFWerLXyiWQYU+0ufsKGM6x8LH8sVmL1bW2Jj2WHmOp6d6bFBcBitYBnD+eO15a6QMkdv52V+aFr6Mq2yugGcGekdmTNIi8FP26RL/88fX+qejDUQRE0M399mXcTxDDtcqHGxDkDmtyMqT42yNhMjPzB7AFZP0QzBXTohF2tFy94wKLmgzB623WRu9nhR6PdkqNBfttAC+EUeFXQSxvxgoO+cUo+I3+8ezX+xZ6uUJa1hA7B0mb88ksIhRieXz10jjjlcsT5EyH6B/sM8NbHtQW1Z5YnTrhPNFmwhkin7TkDqwM2hbg21tem9Ta7l98U8A6O+eFTfwyHuoDu7om80pLTOVg8Uh1T8Ag0qj44kVdlRXAAGSvm4uNqox/j8MTcdM9jz6dzFtsS/88CC7DR3n1UoYJsizeicBLo3fUUgZTdFgbdYQuPtF7Vc2sy1Ky7ANpY5DzwrtwV5n/EgAJeHwgLENtKOXtmSNXYn9NLxWp+0Po/JwzSWpINdJoLHNAhxeqgcUShY9IAb1Q0LgwN9TKUdcLjSo9I/ths8v4+M8XrgESF7Bblz+gMKQq1HxeP1e3VOqgfvCdGErcyZROc+e1/k2MEL86+MYtD3IAhpHLzjsGF7X6cpa/wBFQdMdWFs9X7Dn6fn6P+2PsEpXJSKmtQ992bIjZ969M="
    on_success: always
    on_failure: always

before_install:
- source scripts/ci/environment.sh
- pip install --upgrade docker-compose
- pip install invoke

install: inv dc.build

script: inv test

after_success:
- ci-tag-build
- hub-push
- hub-update-readme
